project:
  type: website
  output-dir: docs

website:
  title: "BIO00056I"
  navbar:
    left:
      - href: index.qmd
        text: "BIO00056I"
        
      - href: workshop5.qmd
        text: "workshop 5"

      - href: workshop6.qmd
        text: "workshop 6"

      - href: workshop7.qmd
        text: "workshop 7"
        
      - href: workshop9.qmd
        text: "workshop 9"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    