project:
  type: website
  output-dir: docs

website:
  title: "BIO00056I"
  navbar:
    left:
      - href: index.qmd
        text: "BIO00087H - home"
        
      - href: BIO56I-gwas-workshop.qmd
        text: "GWAS"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    